(function(){
  var query=new URLSearchParams(location.search),state,world=query.get('world')||'main',view=query.get('view')||'surface',tiles,markers=L.layerGroup(),fitted=false;
  var map=L.map('map',{crs:L.CRS.Simple,minZoom:-3,maxZoom:4,zoomSnap:1,attributionControl:true});
  markers.addTo(map); L.control.attribution().addAttribution('Dynmap-style map for MCGalaxy / ClassiCube');
  function el(id){return document.getElementById(id)}
  function icon(v){return v==='surface'?'block_world_surface.png':v==='flat'?'block_world_flat.png':'block_world_cave.png'}
  function renderViews(){var root=el('views');root.innerHTML='';[['surface','Surface'],['flat','Top-down'],['cave','Cave']].forEach(function(x){var d=document.createElement('div');d.className='view '+(view===x[0]?'active':'');d.innerHTML='<img src="/web/images/'+icon(x[0])+'"><span>'+x[1]+'</span>';d.onclick=function(){view=x[0];renderViews();setLayer()};root.appendChild(d)})}
  function selected(){return state.worlds.filter(function(w){return w.name===world})[0]}
  function setLayer(refit){var w=selected();if(!w)return;if(tiles)map.removeLayer(tiles);el('map').style.background='linear-gradient('+w.sky+','+w.fog+')';var bordered=el('border').checked,border=bordered?'1':'0',dims=(bordered?w.borderViews:w.views)[view],bounds=[[-dims.height,0],[0,dims.width]];tiles=L.imageOverlay('/render/'+encodeURIComponent(world)+'/'+view+'.png?border='+border+'&_='+Date.now(),bounds,{interactive:false}).addTo(map);if(!fitted||refit){map.fitBounds(bounds,{paddingTopLeft:[8,8],paddingBottomRight:[300,8]});fitted=true}drawPlayers()}
  function playerPoint(p,w){var bordered=el('border').checked,pad=bordered?512:0,scale=bordered?1:4,x0=-pad,x1=w.width+pad,y0=0,y1=w.height,z0=-pad,z1=w.length+pad,inc=view==='cave'?Math.PI/3:Math.PI/6;if(view==='flat')return[-((p.x-x0)*scale+1),((-p.z)-(-z1))*scale+1];var su=Math.sin(Math.PI*3/4),cu=Math.cos(Math.PI*3/4),si=Math.sin(inc),co=Math.cos(inc),U=[-su,0,cu],V=[cu*si,co,su*si],minU=Infinity,maxV=-Infinity;[x0,x1].forEach(function(x){[y0,y1].forEach(function(y){[z0,z1].forEach(function(z){minU=Math.min(minU,U[0]*x+U[1]*y+U[2]*z);maxV=Math.max(maxV,V[0]*x+V[1]*y+V[2]*z)})})});var u=U[0]*p.x+U[1]*p.y+U[2]*p.z,v=V[0]*p.x+V[1]*p.y+V[2]*p.z;return[-((maxV-v)*scale+1),(u-minU)*scale+1]}
  function addMarker(p,w,bot){if(p.world!==world)return;var skin=p.skin||p.name,face='https://cdn.classicube.net/face/'+encodeURIComponent(skin)+'.png',label=bot?p.name+' [Bot]':p.name;var html='<div class="player-marker"><img class="marker-face" src="'+face+'"><span>'+label+'</span></div>';L.marker(playerPoint(p,w),{icon:L.divIcon({html:html,className:'',iconSize:[90,48],iconAnchor:[45,48]})}).addTo(markers)}
  function addMob(m,w){if(m.world!==world)return;var model=m.model==='humanoid'?'human':m.model,html='<div class="player-marker mob-marker"><i class="mob-face mob-'+model+'"></i><span>'+model+'</span></div>';L.marker(playerPoint(m,w),{icon:L.divIcon({html:html,className:'',iconSize:[90,48],iconAnchor:[45,48]})}).addTo(markers)}
  function drawPlayers(){markers.clearLayers();var w=selected();if(el('showPlayers').checked)state.players.forEach(function(p){addMarker(p,w,false)});if(el('bots').checked)state.bots.forEach(function(p){addMarker(p,w,true)});if(el('mobs').checked)(state.mobs||[]).forEach(function(m){addMob(m,w)})}
  function sidebar(){var ws=el('world');var old=world;ws.innerHTML='';state.worlds.forEach(function(w){var o=document.createElement('option');o.value=w.name;o.textContent=w.name+' ('+w.width+'x'+w.height+'x'+w.length+')';ws.appendChild(o)});world=state.worlds.some(function(w){return w.name===old})?old:(state.worlds.some(function(w){return w.name==='main'})?'main':(state.worlds[0]&&state.worlds[0].name));ws.value=world;ws.onchange=function(){world=this.value;setLayer(true)};var ps=el('players');ps.innerHTML='';state.players.forEach(function(p){var d=document.createElement('div');d.className='player';d.innerHTML='<img src="https://cdn.classicube.net/face/'+encodeURIComponent(p.name)+'.png"><div><b>'+p.name+'</b><small>'+p.world+' '+p.x+', '+p.y+', '+p.z+'</small></div>';d.onclick=function(){world=p.world;ws.value=world;setLayer(true);map.setView(playerPoint(p,selected()),2)};ps.appendChild(d)});el('status').textContent=state.worlds.length+' worlds | updated '+new Date().toLocaleTimeString()}
  function update(first){fetch('/api/state').then(function(r){return r.json()}).then(function(j){state=j;sidebar();if(first)setLayer();else drawPlayers()}).catch(function(){el('status').textContent='Map server unavailable'})}
  if(query.get('border')==='1')el('border').checked=true;el('border').onchange=function(){setLayer(false)};el('bots').onchange=drawPlayers;el('mobs').onchange=drawPlayers;el('showPlayers').onchange=drawPlayers;el('sidebarToggle').onclick=function(){document.body.classList.toggle('closed');map.invalidateSize()};renderViews();update(true);setInterval(function(){update(false)},3000);
})();
